CREATE PROCEDURE `StpInsertarMarca`( $IDMARCA varchar(45),
$pNOMBRE varchar(45))
BEGIN
IF NOT exists  (SELECT * FROM marca WHERE IDMARCA =$IDMARCA) THEN

INSERT INTO marca
(IDMARCA,NOMBRE)
VALUES($IDMARCA,$pNOMBRE);
ELSE 
SELECT 'EL REGISTRO YA SE ENCUENTRA REGISTRADO EN BD';
END IF;
END$$