DELIMITER $$
CREATE PROCEDURE `StpActualizarProducto` ($IDPRODUCTO varchar(45),
$pNOMBRE varchar(45) ,
$DESCRIPCION varchar(45), 
$PRECIO_UND FLOAT,
$STOCK INT, 
$PESO FLOAT ,
$PRESENTACION varchar(45) ,
$MARCA varchar(45),
$PROVEEDOR varchar(45))
BEGIN
UPDATE `inventario`.`producto`
SET
`NOMBRE` = $pNOMBRE ,
`DESCRIPCION` = $DESCRIPCION ,
`PRECIO_UND` = $PRECIO_UND,
`STOCK` = $STOCK,
`PESO` = $PESO,
`PRESENTACION` =$PRESENTACION,
`MARCA` =$MARCA,
`PROVEEDOR` = $PROVEEDOR
WHERE `IDPRODUCTO` = $IDPRODUCTO;

END$$
DELIMITER ;