DELIMITER $$
CREATE PROCEDURE `StpInsertarProducto`( $IDPRODUCTO varchar(45),
$pNOMBRE varchar(45) ,
$DESCRIPCION varchar(45), 
$PRECIO_UND FLOAT,
$STOCK INT, 
$PESO FLOAT ,
$PRESENTACION varchar(45) ,
$MARCA varchar(45),
$PROVEEDOR varchar(45))
BEGIN
IF NOT exists  (SELECT * FROM producto WHERE IDPRODUCTO =$IDPRODUCTO) THEN

INSERT INTO producto
(IDPRODUCTO,NOMBRE,DESCRIPCION,PRECIO_UND,STOCK,PESO,PRESENTACION,MARCA,PROVEEDOR)
VALUES($IDPRODUCTO,$pNOMBRE,$DESCRIPCION,$PRECIO_UND,$STOCK,$PESO,$PRESENTACION,$MARCA,$PROVEEDOR);
ELSE 
SELECT 'EL REGISTRO YA SE ENCUENTRA REGISTRADO EN BD'; 
END IF;
END$$
DELIMITER ;