CREATE PROCEDURE `StpInsertarPresentacion`( $IDPRESENTACION varchar(45),
$DESCRIPCION varchar(45))
BEGIN
IF NOT exists  (SELECT * FROM presentacion WHERE IDPRESENTACION =$IDPRESENTACION) THEN

INSERT INTO presentacion
(IDPRESENTACION,DESCRIPCION)
VALUES($IDPRESENTACION,$DESCRIPCION);
ELSE 
SELECT 'EL REGISTRO YA SE ENCUENTRA REGISTRADO EN BD';
END IF;
END$$