DELIMITER $$
USE `inventario`$$
CREATE PROCEDURE `StpActualizarProveedor` ($pIDPROVEEDOR varchar(45),
$pNOMBRE varchar(45) ,
$pDIRECCION varchar(45), 
$pTELEFONO varchar(45) ,
$pCORREO_ELECTRONICO varchar(45), 
$pFECHA_REGISTRO datetime ,
$pPAIS varchar(45) ,
$pCEDULA_JURIDICA varchar(45))
BEGIN
UPDATE `inventario`.`proveedor`
SET
`NOMBRE` = $pNOMBRE ,
`DIRECCION` = $pDIRECCION ,
`TELEFONO` = $pTELEFONO,
`CORREO_ELECTRONICO` = $pCORREO_ELECTRONICO,
`FECHA_REGISTRO` = $pFECHA_REGISTRO,
`PAIS` =$pPAIS,
`CEDULA_JURIDICA` =$pCEDULA_JURIDICA
WHERE `IDPROVEEDOR` = $pIDPROVEEDOR;

END$$

DELIMITER ;