DELIMITER $$
USE `inventario`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `StpInsertarProveedor`( $pIDPROVEEDOR varchar(45),
$pNOMBRE varchar(45) ,
$pDIRECCION varchar(45), 
$pTELEFONO varchar(45) ,
$pCORREO_ELECTRONICO varchar(45), 
$pFECHA_REGISTRO datetime ,
$pPAIS varchar(45) ,
$pCEDULA_JURIDICA varchar(45))
BEGIN
IF NOT exists  (SELECT * FROM proveedor WHERE IDPROVEEDOR =$pIDPROVEEDOR) THEN

INSERT INTO proveedor
(IDPROVEEDOR,NOMBRE,DIRECCION,TELEFONO,CORREO_ELECTRONICO,FECHA_REGISTRO,PAIS,CEDULA_JURIDICA)
VALUES($pIDPROVEEDOR,$pNOMBRE,$pDIRECCION,$pTELEFONO,$pCORREO_ELECTRONICO,$pFECHA_REGISTRO,$pPAIS,$pCEDULA_JURIDICA);
ELSE 
SELECT 'EL REGISTRO YA SE ENCUENTRA REGISTRADO EN BD';
END IF;
END$$

DELIMITER ;