DELIMITER $$
USE `inventario`$$
CREATE PROCEDURE `StpActualizarCliente` ($CEDULA varchar(45),
$pNOMBRE varchar(45) ,
$APELLIDOS varchar(45), 
$TELEFONO varchar(45),
$CORREO_ELECTRONICO varchar(45), 
$DIRECCION varchar(45),
$FECHA_REGISTRO datetime ,
$GENERO varchar(45))
BEGIN
UPDATE `inventario`.`cliente`
SET
`NOMBRE` = $pNOMBRE ,
`APELLIDOS` = $APELLIDOS ,
`TELEFONO` = $TELEFONO,
`CORREO_ELECTRONICO` = $CORREO_ELECTRONICO,
`DIRECCION` = $DIRECCION,
`FECHA_REGISTRO` =$FECHA_REGISTRO,
`GENERO` =$GENERO
WHERE `CEDULA` = $CEDULA;

END$$