DELIMITER $$
USE `inventario`$$
 CREATE PROCEDURE `StpInsertarCliente`( $CEDULA varchar(45),
$pNOMBRE varchar(45) ,
$APELLIDOS varchar(45), 
$TELEFONO varchar(45),
$CORREO_ELECTRONICO varchar(45), 
$DIRECCION varchar(45),
$FECHA_REGISTRO datetime ,
$GENERO varchar(45))
BEGIN
IF NOT exists  (SELECT * FROM cliente WHERE CEDULA =$CEDULA) THEN

INSERT INTO cliente
(CEDULA,NOMBRE,APELLIDOS,TELEFONO,CORREO_ELECTRONICO,DIRECCION,FECHA_REGISTRO,GENERO)
VALUES($CEDULA,$pNOMBRE,$APELLIDOS,$TELEFONO,$CORREO_ELECTRONICO,$DIRECCION,$FECHA_REGISTRO,$GENERO);
ELSE 
SELECT 'EL REGISTRO YA SE ENCUENTRA REGISTRADO EN BD';
END IF;
END$$